config/routes.rb
Wordcloud::Application.routes.draw do
  resources :phrases

  resources :brains
  resources :words
  resources :cloud

  root to: 'words#index'
  get 'words/:id/delete', to: 'words#delete'
  get 'cloud/:cloud', to: 'cloud/#index'
  get 'cloud/:cloud/delete', to: 'cloud#delete'
  get 'cloud/:cloud/list', to: 'cloud#list'
  post 'brains/:id/classify', to: 'brains#classify'
  post 'brains/:name/delete_item/:item_index', to: 'brains#delete_item'
  post 'brains/:id/train', to: 'brains#train'
  post 'brains/:id/related', to: 'brains#related'

end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
    http_basic_authenticate_with :name => "boomi", :password => "b00m1"
  # GET /phrases
  # GET /phrases.json
  def index
    @phrases = Phrase.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @phrases }
    end
  end

  # GET /phrases/1
  # GET /phrases/1.json
  def show
    @phrase = Phrase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @phrase }
    end
  end

    # GET /phrases/new
    # GET /phrases/new.json
    def new
        @brain_names = Array.new    
        @phrase = Phrase.new
        @brains = Brain.find(:all)
        @brains.each do |brain|
            @brain_names << [brain.name, brain.id]
        end

        respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @phrase }
        end
    end

  # GET /phrases/1/edit
  def edit
    @brain_names = Array.new
    @brains = Brain.find(:all)
    @phrase = Phrase.find(params[:id])
    @brains.each do |brain|
        @brain_names << [brain.name, brain.id]
    end
  end

    # POST /phrases
    # POST /phrases.json
    def create
        # cgi post
        if params[:brain_name]
            @brain = Brain.where(:name => params[:brain_name]).first
            @phrase = Phrase.new(:text => params[:text],
                                 :category => params[:category],
                                 :brain_id => @brain.id)
        # xml post
        elsif params[:phrase][:brain_name] 
            @brain = Brain.where(:name => params[:phrase][:brain_name]).first
            @phrase = Phrase.new(:text => params[:phrase][:text],
                                 :category => params[:phrase][:category],
                                 :brain_id => @brain.id)
        # web form
        else
            @brain = Brain.find(params[:phrase][:brain_id])
            @phrase = Phrase.new(params[:phrase])
        end

        respond_to do |format|
            if @phrase.save
                classifier = YAML.load(@brain.classifier)
                classifier.add_item(@phrase.text, @phrase.category)
                @brain.classifier = YAML.dump(classifier)
                @brain.save

                format.html { redirect_to @phrase, notice: 'Phrase was successfully created.' }
                format.json { render json: @phrase, status: :created, location: @phrase }
                format.xml { render xml: @phrase, status: :created, location: @phrase }
            else
                format.html { render action: "new" }
                format.json { render json: @phrase.errors, status: :unprocessable_entity }
                format.xml { render xml: @phrase.errors, status: :unprocessable_entity }
            end
        end
    end

  # PUT /phrases/1
  # PUT /phrases/1.json
  def update
    @phrase = Phrase.find(params[:id])
    @brain = @phrase.brain

    respond_to do |format|
      if @phrase.update_attributes(params[:phrase])
        classifier = YAML.load(@brain.classifier).build_index
        format.html { redirect_to @phrase, notice: 'Phrase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phrases/1
  # DELETE /phrases/1.json
  def destroy
    @phrase = Phrase.find(params[:id])
    @phrase.destroy

    respond_to do |format|
      format.html { redirect_to phrases_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/views/phrases/_form.html.erb
<%= form_for(@phrase) do |f| %>
  <% if @phrase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phrase.errors.count, "error") %> prohibited this phrase from being saved:</h2>

      <ul>
      <% @phrase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :text %><br />
      <%= f.text_area :text %>
  </div>

  <div class="field">
      <%= f.label :category %><br />
      <%= f.text_field :category %>
  </div>

  <div class="field">
      <%= f.label :brain %><br />
      <%= f.select :brain_id, options_for_select(@brain_names) %>
  </div>
      

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phrases/edit.html.erb
<h1>Editing phrase</h1>

<%= render 'form' %>

<%= link_to 'Show', @phrase %> |
<%= link_to 'Back', phrases_path %>

app/views/phrases/index.html.erb
<h1>Listing phrases</h1>

<table>
  <tr>
    <th>Text</th>
    <th>Category</th>
    <th>Classifier Name</th>
    <th>Classifier Type</th>
  </tr>

<% @phrases.each do |phrase| %>
  <tr>
    <td><%= phrase.text %></td>
    <td><%= phrase.category %></td>
    <td><%= phrase.brain.name %></td>
    <td><%= phrase.brain.classifier_type %></td>
    <td><%= link_to 'Show', phrase %></td>
    <td><%= link_to 'Edit', edit_phrase_path(phrase) %></td>
    <td><%= link_to 'Destroy', phrase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Phrase', new_phrase_path %>

app/views/phrases/new.html.erb
<h1>New phrase</h1>

<%= render 'form' %>

<%= link_to 'Back', phrases_path %>

app/views/phrases/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_phrase_path(@phrase) %> |
<%= link_to 'Back', phrases_path %>