config/routes.rb
Wordcloud::Application.routes.draw do
  resources :phrases

  resources :brains
  resources :words
  resources :cloud

  root to: 'words#index'
  get 'words/:id/delete', to: 'words#delete'
  get 'cloud/:cloud', to: 'cloud/#index'
  get 'cloud/:cloud/delete', to: 'cloud#delete'
  get 'cloud/:cloud/list', to: 'cloud#list'
  post 'brains/:id/classify', to: 'brains#classify'
  post 'brains/:name/delete_item/:item_index', to: 'brains#delete_item'
  post 'brains/:id/train', to: 'brains#train'
  post 'brains/:id/related', to: 'brains#related'

end

app/controllers/cloud_controller.rb
class CloudController < ApplicationController
    http_basic_authenticate_with :name => "boomi", :password => "b00m1"
    def index
        @words = Word.where(:deleted => false, :cloud => params[:cloud]).order('count desc').limit(1000)
        respond_to do |format|
            format.html
        end
    end

    def delete
        Word.delete_all(:cloud => params[:cloud])
        respond_to do |format|
            format.html { redirect_to :words, notice: 'Cloud was successfully deleted.' }
        end
    end

    def list
        @words = Word.where(:cloud => params[:cloud]).order('count desc').limit(1000)
        respond_to do |format|
            format.html
        end
    end
end

app/helpers/cloud_helper.rb
module CloudHelper
    def scale(count)
        min = 10
        max = 120.0
        (((max - min)/(@words.first.count))*(count - @words.last.count) + min).to_i
    end
end

app/views/cloud/index.html.erb
<h1><%= @words.first.cloud %></h1>
<div id="top">
    <span class="text">Click on a word to remove it from the cloud</span>
    <br/>
    <a href="/words">Home</a>
    <br/>
    <%= link_to 'Delete Cloud', {:action=>"delete", :controller=>"cloud", :cloud => params[:cloud], data: { confirm: 'Are you sure?' }} %>
    <br/>
    <%= link_to 'Word counts', {:action=>"list", :controller=>"cloud", :cloud=>params[:cloud]} %>
    <br/>
    <%= link_to 'New Word', new_word_path %>
</div>
<div id="cloud">
    <% @words.each do |word| %>
        <span class="word" style="font-size:<%= scale(word.count) %>px">
            <a href="/words/<%= word.id %>/delete"><%= word.text %></a>
        </span>&nbsp
    <% end %>
</div>

app/views/cloud/list.html.erb
<h1>Listing words</h1>

<table>
  <tr>
    <th>Text</th>
    <th>Stem</th>
    <th>Count</th>
    <th>Deleted</th>
    <th>Cloud</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @words.each do |word| %>
  <tr>
    <td><%= word.text %></td>
    <td><%= word.stem %></td>
    <td><%= word.count %></td>
    <td><%= word.deleted %></td>
    <td><%= word.cloud %></td>
    <td><%= link_to 'Show', word %></td>
    <td><%= link_to 'Edit', edit_word_path(word) %></td>
    <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Word', new_word_path %>
<br/>
<%= link_to "Back to #{params[:cloud]}", {:action=>"index", :controller=>"cloud", :cloud=> params[:cloud]} %>