config/routes.rb
Wordcloud::Application.routes.draw do
  resources :phrases

  resources :brains
  resources :words
  resources :cloud

  root to: 'words#index'
  get 'words/:id/delete', to: 'words#delete'
  get 'cloud/:cloud', to: 'cloud/#index'
  get 'cloud/:cloud/delete', to: 'cloud#delete'
  get 'cloud/:cloud/list', to: 'cloud#list'
  post 'brains/:id/classify', to: 'brains#classify'
  post 'brains/:name/delete_item/:item_index', to: 'brains#delete_item'
  post 'brains/:id/train', to: 'brains#train'
  post 'brains/:id/related', to: 'brains#related'

end

app/models/brain.rb
class Brain < ActiveRecord::Base
  # attr_accessible :title, :body
    attr_accessible :classifier_type, :name
    has_many :phrases
    
    def categories
        categories = []
        if self.classifier_type == 'LSI'
            c = Marshal.load self.classifier
            c.items.each do |item|
                c.categories_for(item).each do |item|
                    categories << item
                end
            end
        end
        return categories.uniq
    end
end

app/controllers/brains_controller.rb
class BrainsController < ApplicationController
    http_basic_authenticate_with :name => "boomi", :password => "b00m1"
  
  # GET /brains
  # GET /brains.json
  def index
    @brains = Brain.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brains }
    end
  end

  # GET /brains/1
  # GET /brains/1.json
  def show
    @brain = Brain.find(params[:id])
    @classifier = Marshal.load(@brain.classifier)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brain }
    end
  end

  # GET /brains/new
  # GET /brains/new.json
  def new
    @brain = Brain.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brain }
    end
  end

  # GET /brains/1/edit
  def edit
    @brain = Brain.find(params[:id])
  end

  # POST /brains
  # POST /brains.json
  def create
    @brain = Brain.new(params[:brain])
    if @brain.classifier_type == 'LSI'
        lsi = Classifier::LSI.new
        @brain.classifier = Marshal.dump lsi
    elsif @brain.classifier_type == 'Bayes'
        storage = Ankusa::MemoryStorage.new
        bayes = Ankusa::NaiveBayesClassifier.new storage
        @brain.classifier = Marshal.dump bayes
    end

    respond_to do |format|
      if @brain.save
        format.html { redirect_to @brain, notice: 'Brain was successfully created.' }
        format.json { render json: @brain, status: :created, location: @brain }
      else
        format.html { render action: "new" }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brains/1
  # PUT /brains/1.json
  def update
    @brain = Brain.find(params[:id])

    respond_to do |format|
      if @brain.update_attributes(params[:brain])
        format.html { redirect_to @brain, notice: 'Brain was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brains/1
  # DELETE /brains/1.json
  def destroy
    @brain = Brain.find(params[:id])
    @brain.destroy

    respond_to do |format|
      format.html { redirect_to brains_url }
      format.json { head :no_content }
    end
  end

  # POST /brains/:id/classify?text="classify me"
  def classify
      # xml
      if params[:phrase]
          text = params[:phrase][:text]
      elsif params[:text]
          text = params[:text]
      end
      @brain = Brain.find(params[:id])
      classifier = Marshal.load(@brain.classifier)
      @res = classifier.classify(params[:text])
      respond_to do |format|
          format.html { 
              flash[:notice] = @res
              redirect_to @brain
          }
          format.xml { render :locals => {:res => @res} } #classify.xml.builder
      end
  end

  # POST /brains/:id/train?text="stuff"&category="category"
  def train
      # xml
      if params[:phrase]
          text = params[:phrase][:text]
          category = params[:phrase][:category]
      # cgi
      elsif params[:text]
          text = params[:text]
          category = params[:category]
      end
      @brain = Brain.find(params[:id])
      classifier = Marshal.load(@brain.classifier)
      if @brain.classifier_type == 'Bayes'
          classifier.train(category, text)
          @brain.classifier = Marshal.dump(classifier)
      else
        classifier.add_item(text, category)
        classifier.build_index if classifier.needs_rebuild?
        @brain.classifier = Marshal.dump(classifier)
      end
      respond_to do |format|
          if @brain.save
              @res = "success"
              format.html { redirect_to @brain, notice: 'Item successfully added.' }
              format.xml { render :locals => {:res => @res} }
          end
      end
  end

  # POST /brains/:id/related?text="stuff"
  def related
      # xml
      if params[:phrase]
          text = params[:phrase][:text]
          brain_id = params[:phrase][:brain_id]
      elsif params[:text]
          text = params[:text]
          brain_id = params[:id]
      end
      @brain = Brain.find(brain_id)
      classifier = Marshal.load(@brain.classifier)
      if @brain.classifier_type == 'LSI'
          @res = classifier.find_related(text)
      else
          @res = "Only the LSI classifier supports this function."
      end
      respond_to do |format|
          format.xml { render :locals => {:res => @res} }
      end
  end


  # POST /brains/:name/delete_item/:item_index
  def delete_item
    @brain = Brain.where(:name => params[:name]).first
    classifier = YAML.load(@brain.classifier)
    classifier.remove_item(classifier.items[params[:item_index].to_i])
    classifier.build_index if classifier.needs_rebuild?
    @brain.classifier = YAML.dump(classifier)
    respond_to do |format|
        if @brain.save
            format.html { redirect_to @brain, notice: 'Item successfully deleted.' }
        end
    end
  end
end

app/helpers/brains_helper.rb
module BrainsHelper
end

app/views/brains/_classify_form.html.erb
<%= form_tag "/brains/#{@brain.id}/classify" do %>
    <%= label_tag(:text, "Text to test") %><br/>
    <%= text_area_tag(:text) %><br/>
    <%= submit_tag("Classify") %>
<% end %>

app/views/brains/_form.html.erb
<%= form_for(@brain) do |f| %>
  <% if @brain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brain.errors.count, "error") %> prohibited this brain from being saved:</h2>

      <ul>
      <% @brain.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %><br />
  </div>

  <div class="field">
    <%= f.label :classifier_type %><br />
    <%= f.select :classifier_type, options_for_select(["LSI", "Bayes"]) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brains/_train_form.html.erb
<%= form_tag "/brains/#{@brain.id}/train" do %>
    <%= label_tag(:text, "Text to train") %><br/>
    <%= text_area_tag(:text) %><br/>
    <%= label_tag(:text, "Category") %><br/>
    <%= text_field_tag(:category) %><br/>
    <%= submit_tag("Train") %>
<% end %>

app/views/brains/edit.html.erb
<h1>Editing brain</h1>

<%= render 'form' %>

<%= link_to 'Show', @brain %> |
<%= link_to 'Back', brains_path %>

app/views/brains/index.html.erb
<h1>Listing brains</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
  </tr>

<% @brains.each do |brain| %>
    <tr>
        <td><%= brain.name %></td>
        <td><%= brain.classifier_type %></td>  
        <td><%= link_to 'Show', brain %></td>
        <td><%= link_to 'Edit', edit_brain_path(brain) %></td>
        <td><%= link_to 'Destroy', brain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>
</table>

<br />

<%= link_to 'New Brain', new_brain_path %>

app/views/brains/new.html.erb
<h1>New brain</h1>

<%= render 'form' %>

<%= link_to 'Back', brains_path %>

app/views/brains/show.html.erb
<h1><%= @brain.name %></h1>

<%= render "train_form" %>
<br/>
<%= render "classify_form" %>

<div id="results">
    <p id="notice"><%= notice %></p>
</div>

<%= link_to 'Edit', edit_brain_path(@brain) %> |
<%= link_to 'Back', brains_path %>